// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfrtc2HeqC2XgYhfpTaahLs5MpfTp4dAM',
    appId: '1:479684265023:web:030cd4ebab03c3981fe48a',
    messagingSenderId: '479684265023',
    projectId: 'chat-app-8b3d4',
    authDomain: 'chat-app-8b3d4.firebaseapp.com',
    storageBucket: 'chat-app-8b3d4.appspot.com',
    measurementId: 'G-MM25QKEWX3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5qmwL8UKdCOQo9JeVLCQA9_lfXLZmD9M',
    appId: '1:479684265023:android:0bd04618ff44b3ac1fe48a',
    messagingSenderId: '479684265023',
    projectId: 'chat-app-8b3d4',
    storageBucket: 'chat-app-8b3d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_K0sdKFDlYFUX_WGwzPqUfVworkBWslY',
    appId: '1:479684265023:ios:3c3cfe545e5850961fe48a',
    messagingSenderId: '479684265023',
    projectId: 'chat-app-8b3d4',
    storageBucket: 'chat-app-8b3d4.appspot.com',
    iosClientId: '479684265023-vqi6mc47a15fs7vgl7039n4favukvcdi.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
